/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2014-08-10 15:18:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import org.apache.commons.lang3.StringUtils;
import modelo.Equipo;
import modelo.utils.Util;
import modelo.Moneda;
import modelo.Precio;
import modelo.Caracteristica;
import modelo.ArchivoGrupoEquipo;
import java.util.List;
import modelo.GrupoEquipo;
import modelo.Usuario;
import modelo.utils.Traductor;
import modelo.utils.Traductor;
import modelo.utils.Traductor;
import modelo.utils.Traductor;
import modelo.utils.Traductor;
import modelo.Usuario;
import modelo.utils.Traductor;

public final class agregar_005fproducto_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/jsp/plantillas/encabezado.jsp", Long.valueOf(1397991058000L));
    _jspx_dependants.put("/jsp/scripts/utils/validaciones.jsp", Long.valueOf(1398973020000L));
    _jspx_dependants.put("/jsp/plantillas/botonera_principal.jsp", Long.valueOf(1407594474000L));
    _jspx_dependants.put("/jsp/plantillas/obj_idioma.jsp", Long.valueOf(1397991058000L));
    _jspx_dependants.put("/jsp/scripts/agregar_producto.jsp", Long.valueOf(1399020113000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');
      out.write('	');
      out.write('\n');

	Traductor traductor = (Traductor) session.getAttribute("traductor");
	String[] idioma_pais = new String[2];
	String strIdiomaPais = "";
	if(traductor == null){
		String cookieName = "cookie_idioma_pais";
		Cookie cookies[] = request.getCookies();
		Cookie myCookie = null;
		if (cookies != null) {
			for (int i = 0; i < cookies.length; i++) {
				if (cookies[i].getName().equals(cookieName)) {
					myCookie = cookies[i];
					break;
				}
			}
		}
	
	
		if (myCookie == null) {
			traductor = new Traductor();
			idioma_pais[0] = traductor.getIdioma();
			idioma_pais[1] = traductor.getPais();
			myCookie = new Cookie(cookieName, idioma_pais[0] + "_"
					+ idioma_pais[1]);
			myCookie.setMaxAge(Integer.MAX_VALUE);
			response.addCookie(myCookie);
		} else {
			idioma_pais = myCookie.getValue().split("_");
			traductor = new Traductor(idioma_pais[0], idioma_pais[1]);
		}
		
		
		
	}else{
		idioma_pais[0] = traductor.getIdioma();
		idioma_pais[1] = traductor.getPais();
	}
	
		strIdiomaPais = idioma_pais[0] + "_" + idioma_pais[1];


	String[] idiomasDisponibles = traductor
			.getIdiomasPaisesDisponibles();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>");
      out.print(traductor.traducir("agregar_producto"));
      out.write("</title>\n");
      out.write("<link type=\"text/css\" rel=\"StyleSheet\"\n");
      out.write("\thref=\"../css/plantillas/encabezado.css\">\n");
      out.write("<link type=\"text/css\" rel=\"StyleSheet\"\n");
      out.write("\thref=\"../css/plantillas/cuerpo.css\">\n");
      out.write("<link type=\"text/css\" rel=\"StyleSheet\"\n");
      out.write("\thref=\"../css/plantillas/botonera_principal.css\">\n");
      out.write("<link type=\"text/css\" rel=\"StyleSheet\"\n");
      out.write("\thref=\"../css/plantillas/ubicacion.css\">\n");
      out.write("<link type=\"text/css\" rel=\"StyleSheet\" href=\"../css/utils/errores.css\">\n");
      out.write("<link type=\"text/css\" rel=\"StyleSheet\" href=\"../css/utils/utils.css\">\n");
      out.write("\n");
      out.write("<link type=\"text/css\" rel=\"StyleSheet\"\n");
      out.write("\thref=\"../css/agregar_producto.css\">\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"../js/utils/utils.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"../js/utils/validaciones.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"../js/utils/cookies.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"../js/utils/contenido_dinamico.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"../js/plantillas/idioma_pais.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"../js/agregar_producto.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"../js/ajax/set_idioma_pais_ajax.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tvar cargando = \"");
      out.print(traductor.traducir("cargando"));
      out.write("\";\n");
      out.write("\tvar el_campo = \"");
      out.print(traductor.traducir("el_campo"));
      out.write("\";\n");
      out.write("\tvar es_requerido = \"");
      out.print(traductor.traducir("es_requerido"));
      out.write("\";\n");
      out.write("\tvar mensaje_email_invalido = \"");
      out.print(traductor.traducir("mensaje_email_invalido"));
      out.write("\";\n");
      out.write("\tvar titulo_errores_formulario = \"");
      out.print(traductor.traducir("titulo_errores_formulario"));
      out.write("\";\n");
      out.write("\tvar error_validar_imagen_parte1 = \"");
      out.print(traductor.traducir("error_validar_imagen_parte1"));
      out.write("\";\n");
      out.write("\tvar error_validar_video_parte1 = \"");
      out.print(traductor.traducir("error_validar_video_parte1"));
      out.write("\";\n");
      out.write("\tvar error_validar_archivo_parte1 = \"");
      out.print(traductor.traducir("error_validar_archivo_parte1"));
      out.write("\";\n");
      out.write("\tvar error_validar_archivo_parte2 = \"");
      out.print(traductor.traducir("error_validar_archivo_parte2"));
      out.write("\";\n");
      out.write("</script>");
      out.write('\n');
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tvar agregar_producto_error1 = \"");
      out.print(traductor.traducir("agregar_producto_error1"));
      out.write("\";\n");
      out.write("\tvar agregar_producto_error2 = \"");
      out.print(traductor.traducir("agregar_producto_error2"));
      out.write("\";\n");
      out.write("</script>");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body onload=\"verificarEstadoCampos();\">\n");
      out.write("\t");

try {
		Usuario usuario = (Usuario) session.getAttribute("usuario");
		GrupoEquipo grupoEquipo = (GrupoEquipo) session
				.getAttribute("grupoEquipo");
	
      out.write('\n');
      out.write('	');
      out.write("\n");
      out.write("\t\n");
      out.write("<div class=\"encabezado\">\n");
      out.write("\t<div class=\"texto_encabezado\">\n");
      out.write("\t\t<div class=\"titulo_encabezado\">");
      out.print(traductor.traducir("nombre_sistema") );
      out.write("</div>\n");
      out.write("\t\t<div class=\"subtitulo_encabezado\">");
      out.print(traductor.traducir("consola_administrativa") );
      out.write("</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"select_idiomas\">\n");
      out.write("\t\t<select id=\"select_idioma\" onchange=\"setIdiomaPais(this);\">\n");
      out.write("\t\t\t");

				for (int i = 0; i < idiomasDisponibles.length; i++) {
			
      out.write("\n");
      out.write("\t\t\t<option value=\"");
      out.print(idiomasDisponibles[i]);
      out.write("\"\n");
      out.write("\t\t\t\t");
if (idiomasDisponibles[i].equals(strIdiomaPais)) {
      out.write("\n");
      out.write("\t\t\t\tselected=\"selected\" ");
}
      out.write(">\n");
      out.write("\t\t\t\t");

					if (idiomasDisponibles[i].trim().length() > 0) {
							String idioma_pais2[] = idiomasDisponibles[i].split("_");
							Traductor t = new Traductor(idioma_pais2[0], idioma_pais2[1]);
							out.print(t.traducir(idioma_pais2[0]) + ", "
									+ t.traducir(idioma_pais2[1]));
						} else {
							out.print(traductor.traducir("default"));
						}
				
      out.write("\n");
      out.write("\t\t\t</option>\n");
      out.write("\t\t\t");

				}
			
      out.write("\n");
      out.write("\n");
      out.write("\t\t</select>\n");
      out.write("\t</div>\n");
      out.write("</div>");
      out.write('\n');
      out.write('	');
      out.write('\n');
      out.write('\n');
      out.write('\n');
 //Usuario usuario = (Usuario) session.getAttribute("usuario");
      out.write("\n");
      out.write("<div class=\"botonera_principal\">\n");
      out.write("\t<h3 class=\"usuario_botonera\">");
      out.print(usuario.getNombre() + " " + usuario.getApellido() );
      out.write(" </h3>\n");
      out.write("\t<ul>\n");
      out.write("\t\t<li><a href=\"agregar_producto.jsp\">");
      out.print(traductor.traducir("agregar_producto"));
      out.write("</a></li>\n");
      out.write("\t\t<li><a href=\"listado_productos.jsp\">");
      out.print(traductor.traducir("listado_productos"));
      out.write("</a></li>\n");
      out.write("\t\t<li><a href=\"administrar_documentos_productos.jsp\">");
      out.print(traductor.traducir("administrar_documentos_productos"));
      out.write("</a></li>\n");
      out.write("\t\t<li><a href=\"listado_categoria.jsp\">");
      out.print(traductor.traducir("listado_categoria"));
      out.write("</a></li>\n");
      out.write("\t\t<li><a href=\"personalizar_pantallas.jsp\">");
      out.print(traductor.traducir("personalizar_pantallas_mt"));
      out.write("</a></li>\n");
      out.write("\t\t<li><a href=\"agregar_administrador.jsp\">");
      out.print(traductor.traducir("agregar_administrador"));
      out.write("</a></li>\n");
      out.write("\t\t<li><a href=\"listado_administradores.jsp\">");
      out.print(traductor.traducir("listado_administradores"));
      out.write("</a></li>\n");
      out.write("\t\t<li><a\n");
      out.write("\t\t\thref=\"");
      out.print(request.getContextPath() );
      out.write("/AutenticarUsuarioServlet\">");
      out.print(traductor.traducir("cerrar_sesion"));
      out.write("</a></li>\n");
      out.write("\t</ul>\n");
      out.write("</div>");
      out.write("\n");
      out.write("\t<div id=\"cuerpo\">\n");
      out.write("\t\t<div>\n");
      out.write("\t\t\t<span class=\"ubicacion\"> ");
if(request.getParameter("catalogo_productos_servidor.productos.id_producto") == null){ 
      out.write("\n");
      out.write("\t\t\t\t<a href=\"home.jsp\">");
      out.print(traductor.traducir("home"));
      out.write("</a> &gt;&gt; <b>");
      out.print(traductor.traducir("agregar_producto"));
      out.write("</b>\n");
      out.write("\t\t\t\t");
}else{ 
      out.write(" <a href=\"listado_productos.jsp\">");
      out.print(traductor.traducir("listado_productos"));
      out.write("</a>\n");
      out.write("\t\t\t\t&gt;&gt; <b>");
      out.print(traductor.traducir("editar_producto"));
      out.write("</b> ");
} 
      out.write("\n");
      out.write("\t\t\t</span>\n");
      out.write("\t\t\t<div class=\"grupo_equipos\">\n");
      out.write("\t\t\t\t<b>");
      out.print(traductor.traducir("grupo_de_equipos"));
      out.write(":</b>\n");
      out.write("\t\t\t\t");
      out.print(grupoEquipo.getNombre());
      out.write("</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- <center>  -->\n");
      out.write("\t\t<div style=\"text-align: center; margin: auto;\">\n");
      out.write("\t\t\t<div id=\"error\" class=\"error\"></div>\n");
      out.write("\t\t\t<h2>\n");
      out.write("\t\t\t\t");
if(request.getParameter("catalogo_productos_servidor.productos.id_producto") == null){ 
      out.write("\n");
      out.write("\t\t\t\t");
      out.print(traductor.traducir("mensaje_agregar_producto"));
      out.write("\n");
      out.write("\t\t\t\t");
}else{ 
      out.write("\n");
      out.write("\t\t\t\t");
      out.print(traductor.traducir("mensaje_editar_producto"));
      out.write("\n");
      out.write("\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t</h2>\n");
      out.write("\t\t\t<form method=\"post\" onsubmit=\"return validarAgregarProducto(this);\"\n");
      out.write("\t\t\t\taction=\"");
      out.print(request.getContextPath() );
      out.write('/');
      out.print((request.getParameter("catalogo_productos_servidor.productos.id_producto") == null)?"AgregarProductoServlet":"EditarProductoServlet" );
      out.write("\"\n");
      out.write("\t\t\t\tenctype=\"multipart/form-data\">\n");
      out.write("\t\t\t\t");
if(request.getParameter("catalogo_productos_servidor.productos.id_producto") != null){ 
      out.write("\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"id_producto\"\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print(request.getParameter("catalogo_productos_servidor.productos.id_producto"));
      out.write("\">\n");
      out.write("\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t<table style=\"margin: auto;\">\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<th class=\"lbl_usuario\">");
      out.print(traductor.traducir("logotipo") );
      out.write(":</th>\n");
      out.write("\t\t\t\t\t\t<td align=\"left\"><input required=\"required\" type=\"file\"\n");
      out.write("\t\t\t\t\t\t\tid=\"logotipo\"\n");
      out.write("\t\t\t\t\t\t\tname=\"");
      out.print(Util.convertirANombreCampo(traductor.traducir("logotipo")) );
      out.write("_norequerido\"\n");
      out.write("\t\t\t\t\t\t\tonchange=\"llenoArchivoLogo(this);\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"list_img\">\n");
      out.write("\t\t\t\t\t\t\t\t<table>\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										List<ArchivoGrupoEquipo> archivoGrupoEquipos = grupoEquipo
												.getArchivoGrupoEquipoPorTipoArchivo(new String[] { "img" });
										for (int i = 0; i < archivoGrupoEquipos.size(); i++) {
									
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th><input type=\"checkbox\" name=\"checkbox_logo\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(archivoGrupoEquipos.get(i).getArchivo().getMd5());
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonchange=\"seleccionoCheckBoxLogo(this);\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
      out.print((archivoGrupoEquipos.get(i).getArchivo().getRuta().equals(request.getParameter("catalogo_productos_servidor.archivos.ruta")))?" checked=\"checked\"":"" );
      out.write(">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th><a target=\"_blank\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\thref=\"../");
      out.print(archivoGrupoEquipos.get(i).getArchivo().getRuta() );
      out.write("\"><img\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\talt=\"logo_");
      out.print((i+1) );
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tsrc=\"../");
      out.print(archivoGrupoEquipos.get(i).getArchivo().getRuta() );
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"logo\"></a></th>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>");
      out.print(archivoGrupoEquipos.get(i).getNombreOriginal());
      out.write("</td>\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
									
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t</table>\n");
      out.write("\t\t\t\t\t\t\t</div></td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<th class=\"lbl_usuario\">");
      out.print(traductor.traducir("nombre") );
      out.write(":</th>\n");
      out.write("\t\t\t\t\t\t<td align=\"left\"><input type=\"text\" required=\"required\"\n");
      out.write("\t\t\t\t\t\t\tname=\"");
      out.print(Util.convertirANombreCampo(traductor.traducir("nombre")) );
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\tvalue=\"");
      out.print((request.getParameter("catalogo_productos_servidor.productos.nombre") == null)?"":request.getParameter("catalogo_productos_servidor.productos.nombre") );
      out.write("\"></td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t<th class=\"lbl_usuario\">");
      out.print(traductor.traducir("descripcion") );
      out.write(":</th>\n");
      out.write("\t\t\t\t\t\t<td align=\"left\"><textarea required=\"required\"\n");
      out.write("\t\t\t\t\t\t\t\tname=\"");
      out.print(Util.convertirANombreCampo(traductor.traducir("descripcion")) );
      out.write('"');
      out.write('>');
      out.print((request.getParameter("catalogo_productos_servidor.productos.descripcion") == null)?"":request.getParameter("catalogo_productos_servidor.productos.descripcion") );
      out.write("</textarea></td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t");
 String arregloIdProductoXEquipos[] = request.getParameterValues("catalogo_productos_servidor.productos_x_equipos.id_producto_x_equipo");
						String arregloIdEquipos[] = request.getParameterValues("catalogo_productos_servidor.equipos.id_equipo"); 
						Set<String> setIdProductoXEquipos = null;
						if(arregloIdProductoXEquipos != null){
							setIdProductoXEquipos =  new HashSet<String>(Arrays.asList(arregloIdProductoXEquipos));
						}
						Set<String> setIdEquipos = null;
						if(arregloIdEquipos != null){
							setIdEquipos = new HashSet<String>(Arrays.asList(arregloIdEquipos));
						}
						
      out.write("\n");
      out.write("\t\t\t\t\t\t<th class=\"lbl_usuario\">");
      out.print(traductor.traducir("equipo") );
      out.write(":</th>\n");
      out.write("\t\t\t\t\t\t<td align=\"left\"><select required=\"required\"\n");
      out.write("\t\t\t\t\t\t\tmultiple=\"multiple\"\n");
      out.write("\t\t\t\t\t\t\tname=\"");
      out.print(Util.convertirANombreCampo(traductor.traducir("equipo")) );
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t");
 List<Equipo> equipos = Equipo.getEquiposPertenecenAGrupoEquipo(grupoEquipo.getId());
									for(int i = 0; i < equipos.size(); i++){
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"");
      out.print(equipos.get(i).getId());
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print((setIdEquipos != null && setIdEquipos.contains(Integer.toString(equipos.get(i).getId())))?" selected=\"selected\"":"" );
      out.write('>');
      out.print(equipos.get(i).getNombre() );
      out.write("</option>\n");
      out.write("\t\t\t\t\t\t\t\t");
}
      out.write("\n");
      out.write("\t\t\t\t\t\t</select> ");
if(arregloIdProductoXEquipos != null){
								Object obj[] = setIdProductoXEquipos.toArray();
								Arrays.sort(obj);
      out.write(" <input type=\"hidden\"\n");
      out.write("\t\t\t\t\t\t\tname=\"id_producto_x_equipos\"\n");
      out.write("\t\t\t\t\t\t\tvalue=\"");
      out.print(StringUtils.join(obj, ',') );
      out.write('"');
      out.write('>');
      out.write(' ');
}
      out.write("</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t");
 String arregloIdProductoXCaracteristicas[] = request.getParameterValues("catalogo_productos_servidor.productos_x_caracteristicas.id_producto_x_caracteristica");
						String arregloIdCaracteristicas[] = request.getParameterValues("catalogo_productos_servidor.caracteristicas.id_caracteristica");
						String arregloValores[] = request.getParameterValues("catalogo_productos_servidor.productos_x_caracteristicas.valor"); 
						Set<String> setIdProductoXCaracteristicas = new HashSet<String>(); 
						
						 List<Caracteristica> caracteristicas = Caracteristica
										.getCaracteristicas(); 
      out.write("\n");
      out.write("\t\t\t\t\t\t<th class=\"lbl_usuario\">");
      out.print(traductor.traducir("caracteristicas") );
      out.write(":</th>\n");
      out.write("\t\t\t\t\t\t<td align=\"left\"><a\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:agregarContenidoDinamico(0);\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"tipo_titulo\">");
      out.print(traductor.traducir("agregar") );
      out.write("</a> <a\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:quitarContenidoDinamico(0);\" class=\"tipo_titulo\">");
      out.print(traductor.traducir("quitar") );
      out.write("</a>\n");
      out.write("\t\t\t\t\t\t\t<div id=\"campos_caracteristicas\">\n");
      out.write("\t\t\t\t\t\t\t\t");
if(arregloIdProductoXCaracteristicas != null){
								for(int i = 0; i < arregloIdProductoXCaracteristicas.length; i++){ 
									if(setIdProductoXCaracteristicas.add(arregloIdProductoXCaracteristicas[i])){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<!--inicio_");
      out.print(setIdProductoXCaracteristicas.size() );
      out.write("-->\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"contenido_caracteristicas\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<select\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"");
      out.print(Util.convertirANombreCampo(traductor.traducir("caracteristica")) );
      out.write('_');
      out.print(setIdProductoXCaracteristicas.size() );
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"caracteristica_");
      out.print(setIdProductoXCaracteristicas.size() );
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\trequired=\"required\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">");
      out.print(traductor.traducir("seleccione_una_caracteristica") );
      out.write("</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
for (int j = 0; j < caracteristicas.size(); j++) {
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(caracteristicas.get(j).getId() );
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print((Integer.parseInt(arregloIdCaracteristicas[i]) == caracteristicas.get(j).getId())?" selected=\"selected\"":"" );
      out.write('>');
      out.print(caracteristicas.get(j).getNombre() );
      out.write("</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select> <input type=\"text\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"visibility: hidden; display: none; width: 0px; height: 0px;\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"");
      out.print(Util.convertirANombreCampo(traductor.traducir("nueva_caracteristica")) );
      out.write('_');
      out.print(setIdProductoXCaracteristicas.size() );
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"nueva_caracteristica_");
      out.print(setIdProductoXCaracteristicas.size() );
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonchange=\"ocultarMostrar(this, new Array('caracteristica_");
      out.print(setIdProductoXCaracteristicas.size() );
      out.write("'), new Array('nueva_caracteristica_");
      out.print(setIdProductoXCaracteristicas.size() );
      out.write("'));\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"true\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"");
      out.print(Util.convertirANombreCampo(traductor.traducir("es_nueva_caracteristica")) );
      out.write('_');
      out.print(setIdProductoXCaracteristicas.size() );
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(traductor.traducir("nueva_preguntando") );
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"tipo_titulo\">");
      out.print(traductor.traducir("valor") );
      out.write(":\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"text\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"");
      out.print(Util.convertirANombreCampo(traductor.traducir("valor_caracteristica")) );
      out.write('_');
      out.print(setIdProductoXCaracteristicas.size() );
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\trequired=\"required\" value=\"");
      out.print(arregloValores[i] );
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<!--fin_");
      out.print(setIdProductoXCaracteristicas.size() );
      out.write("-->\n");
      out.write("\t\t\t\t\t\t\t\t");
 }
									}
								} 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div> ");
if(arregloIdProductoXCaracteristicas != null){
								Object obj[] = setIdProductoXCaracteristicas.toArray();
								Arrays.sort(obj);
      out.write(" <input type=\"hidden\"\n");
      out.write("\t\t\t\t\t\t\tname=\"id_producto_x_caracteristicas\"\n");
      out.write("\t\t\t\t\t\t\tvalue=\"");
      out.print(StringUtils.join(obj, ',') );
      out.write('"');
      out.write('>');
      out.write(' ');
}
      out.write("</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t\t");
 String arregloIdPreciosProducto[] = request.getParameterValues("catalogo_productos_servidor.precios_productos.id_precio_producto");
						String arregloNombresPrecios[] = request.getParameterValues("catalogo_productos_servidor.precios_productos.nombre");
						String arregloCodigoMonedas[] = request.getParameterValues("catalogo_productos_servidor.precios_productos.codigo_moneda");
						String arregloValoresPrecios[] = request.getParameterValues("catalogo_productos_servidor.precios_productos.valor");
						Set<String> setIdPrecioProductos = new HashSet<String>(); 
						
						 List<Moneda> monedas = Moneda.getMonedas(); 
      out.write("\n");
      out.write("\t\t\t\t\t\t<th class=\"lbl_usuario\">");
      out.print(traductor.traducir("precios") );
      out.write(":</th>\n");
      out.write("\t\t\t\t\t\t<td align=\"left\"><a\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:agregarContenidoDinamico(1);\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"tipo_titulo\">");
      out.print(traductor.traducir("agregar") );
      out.write("</a> <a\n");
      out.write("\t\t\t\t\t\t\thref=\"javascript:quitarContenidoDinamico(1);\" class=\"tipo_titulo\">");
      out.print(traductor.traducir("quitar") );
      out.write("</a>\n");
      out.write("\t\t\t\t\t\t\t<div id=\"campos_precios\">\n");
      out.write("\t\t\t\t\t\t\t\t");
if(arregloIdPreciosProducto != null){
									for(int i = 0; i < arregloIdPreciosProducto.length; i++){ 
										if(setIdPrecioProductos.add(arregloIdPreciosProducto[i])){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t<!--inicio_");
      out.print(setIdPrecioProductos.size() );
      out.write("-->\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"contenido_precios\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"tipo_titulo\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(traductor.traducir("nombre") );
      out.write(": <input type=\"text\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"");
      out.print(Util.convertirANombreCampo(traductor.traducir("nombre_precio")) );
      out.write('_');
      out.print(setIdPrecioProductos.size() );
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\trequired=\"required\" value=\"");
      out.print(arregloNombresPrecios[i] );
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"tipo_titulo\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(traductor.traducir("valor") );
      out.write(": <input type=\"number\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonkeypress=\"return soloNumerosConDecimales(event);\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"");
      out.print(Util.convertirANombreCampo(traductor.traducir("valor_precio")) );
      out.write('_');
      out.print(setIdPrecioProductos.size() );
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstep=\"any\" required=\"required\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(arregloValoresPrecios[i] );
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"tipo_titulo\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\tmoneda: <select\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"");
      out.print(traductor.traducir("moneda") );
      out.write('_');
      out.print(setIdPrecioProductos.size() );
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"moneda_");
      out.print(setIdPrecioProductos.size() );
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\trequired=\"required\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"\">");
      out.print(traductor.traducir("seleccione_una_moneda"));
      out.write("</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
for(int j = 0; j < monedas.size(); j++){ 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(monedas.get(j).getCodigo() );
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(arregloCodigoMonedas[i].equals(monedas.get(j).getCodigo())?" selected=\"selected\"":"" );
      out.write('>');
      out.print(monedas.get(j).getNombre() );
      out.write("</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"visibility: hidden; display: none; width: 0px; height: 0px;\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tid=\"div_nueva_moneda_");
      out.print(setIdPrecioProductos.size() );
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"tipo_titulo\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(traductor.traducir("codigo_moneda"));
      out.write(": <input type=\"text\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tmaxlength=\"10\" size=\"6\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"");
      out.print(Util.convertirANombreCampo(traductor.traducir("codigo_nueva_moneda")) );
      out.write('_');
      out.print(setIdPrecioProductos.size() );
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"tipo_titulo\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(traductor.traducir("nombre_moneda"));
      out.write(": <input type=\"text\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"");
      out.print(Util.convertirANombreCampo(traductor.traducir("nombre_nueva_moneda")) );
      out.write('_');
      out.print(setIdPrecioProductos.size() );
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"tipo_titulo\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(traductor.traducir("simbolo_moneda"));
      out.write(": <input\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"text\" maxlength=\"10\" size=\"6\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"");
      out.print(Util.convertirANombreCampo(traductor.traducir("simbolo_nueva_moneda")) );
      out.write('_');
      out.print(setIdPrecioProductos.size() );
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"tipo_titulo\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
      out.print(traductor.traducir("valor_moneda"));
      out.write(": <input\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"number\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tonkeypress=\"return soloNumerosConDecimales(event);\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tstep=\"any\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tname=\"");
      out.print(Util.convertirANombreCampo(traductor.traducir("valor_nueva_moneda")) );
      out.write('_');
      out.print(setIdPrecioProductos.size() );
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<input type=\"checkbox\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tonchange=\"ocultarMostrar(this, Array('moneda_");
      out.print(setIdPrecioProductos.size() );
      out.write("'), Array('div_nueva_moneda_");
      out.print(setIdPrecioProductos.size() );
      out.write("'));\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvalue=\"true\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tname=\"");
      out.print(Util.convertirANombreCampo(traductor.traducir("es_nueva_moneda")) );
      out.write('_');
      out.print(setIdPrecioProductos.size() );
      out.write("\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(traductor.traducir("nueva_preguntando"));
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<!--fin_");
      out.print(setIdPrecioProductos.size() );
      out.write("-->\n");
      out.write("\t\t\t\t\t\t\t\t");
 }
									}
								} 
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div> ");
if(arregloIdPreciosProducto != null){
								Object obj[] = setIdPrecioProductos.toArray();
								Arrays.sort(obj);
      out.write(" <input type=\"hidden\"\n");
      out.write("\t\t\t\t\t\t\tname=\"id_precios_producto\"\n");
      out.write("\t\t\t\t\t\t\tvalue=\"");
      out.print(StringUtils.join(obj, ',') );
      out.write('"');
      out.write('>');
      out.write(' ');
}
      out.write("</td>\n");
      out.write("\t\t\t\t\t</tr>\n");
      out.write("\t\t\t\t</table>\n");
      out.write("\t\t\t\t<br> <input type=\"submit\"\n");
      out.write("\t\t\t\t\tvalue=\"");
      out.print((request.getParameter("catalogo_productos_servidor.productos.id_producto") == null)?traductor.traducir("agregar_producto"):traductor.traducir("editar_producto") );
      out.write("\">\n");
      out.write("\t\t\t\t<input type=\"reset\" value=\"");
      out.print(traductor.traducir("reset") );
      out.write("\">\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- </center> -->\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\tminContenido[0] = 0;\n");
      out.write("\t\tnumContenido[0] = ");
      out.print(setIdProductoXCaracteristicas.size() );
      out.write(";\n");
      out.write("\t\tidDivContenedor[0] = \"campos_caracteristicas\";\n");
      out.write("\t\thtmlContenido[0] = \"<div class=\\\"contenido_caracteristicas\\\">\" + \n");
      out.write("\t\t\"<div>\"+\n");
      out.write("\t\t\"<select required=\\\"required\\\" id=\\\"caracteristica_numContenido\\\" name=\\\"");
      out.print(Util.convertirANombreCampo(traductor.traducir("caracteristica")) );
      out.write("_numContenido\\\">\"\n");
      out.write("\t\t\t\t+ \"<option value=\\\"\\\">");
      out.print(traductor.traducir("seleccione_una_caracteristica") );
      out.write("</option>\" +\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t");

				for (int i = 0; i < caracteristicas.size(); i++) {
			
      out.write("\n");
      out.write("\t\t\t\t\"<option value=\\\"");
      out.print(caracteristicas.get(i).getId());
      out.write('\\');
      out.write('"');
      out.write('>');
      out.print(caracteristicas.get(i).getNombre());
      out.write("\"+\n");
      out.write("\t\t\"</option>\"+\n");
      out.write("\t");
}
      out.write("\n");
      out.write("\t\t\"</select>\"+\n");
      out.write("\t\t\"<input id=\\\"nueva_caracteristica_numContenido\\\" type=\\\"text\\\" name=\\\"");
      out.print(Util.convertirANombreCampo(traductor.traducir("nueva_caracteristica")) );
      out.write("_numContenido\\\" style=\\\"visibility: hidden; display: none; width: 0px; height: 0px;\\\">\"+\n");
      out.write("\t\t\n");
      out.write("\t\t\"<input type=\\\"checkbox\\\" name=\\\"");
      out.print(Util.convertirANombreCampo(traductor.traducir("es_nueva_caracteristica")) );
      out.write("_numContenido\\\" value=\\\"true\\\" onchange=\\\"ocultarMostrar(this, new Array('caracteristica_numContenido'), new Array('nueva_caracteristica_numContenido'));\\\"> ");
      out.print(traductor.traducir("nueva_preguntando") );
      out.write("\"+\n");
      out.write("\t\t\"</div>\"\n");
      out.write("\t\t+\"<div class=\\\"tipo_titulo\\\">");
      out.print(traductor.traducir("valor") );
      out.write(": <input required=\\\"required\\\" type=\\\"text\\\" name=\\\"");
      out.print(Util.convertirANombreCampo(traductor.traducir("valor_caracteristica")) );
      out.write("_numContenido\\\">\"\n");
      out.write("\t\t\t\t+ \"</div></div>\";\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\tminContenido[1] = 0;\n");
      out.write("\t\tnumContenido[1] = ");
      out.print(setIdPrecioProductos.size() );
      out.write(";\n");
      out.write("\t\tidDivContenedor[1] = \"campos_precios\";\t\n");
      out.write("\t\thtmlContenido[1] = \"<div class=\\\"contenido_precios\\\">\"+\n");
      out.write("\t\t\t\"<div class=\\\"tipo_titulo\\\">\"+\n");
      out.write("\t\t\"");
      out.print(traductor.traducir("nombre") );
      out.write(": <input required=\\\"required\\\" type=\\\"text\\\" name=\\\"");
      out.print(Util.convertirANombreCampo(traductor.traducir("nombre_precio")) );
      out.write("_numContenido\\\">\"+\n");
      out.write("\t\"</div>\"+\n");
      out.write("\t\"<div class=\\\"tipo_titulo\\\">\"+\n");
      out.write("\t\t\"");
      out.print(traductor.traducir("valor") );
      out.write(": <input required=\\\"required\\\" type=\\\"number\\\" step=\\\"any\\\" name=\\\"");
      out.print(Util.convertirANombreCampo(traductor.traducir("valor_precio")) );
      out.write("_numContenido\\\"\"+\n");
      out.write("\t\t\t\"onkeypress=\\\"return soloNumerosConDecimales(event);\\\">\"+\n");
      out.write("\t\"</div>\"+\n");
      out.write("\t\"<div class=\\\"tipo_titulo\\\">\"+\n");
      out.write("\t\t\"");
      out.print(traductor.traducir("moneda") );
      out.write(": <select required=\\\"required\\\" id=\\\"moneda_numContenido\\\" name=\\\"");
      out.print(Util.convertirANombreCampo(traductor.traducir("moneda")) );
      out.write("_numContenido\\\">\"+\n");
      out.write("\t\t\t\"<option value=\\\"\\\">");
      out.print(traductor.traducir("seleccione_una_moneda"));
      out.write("</option>\"+\n");
      out.write("\t\t");
for(int i = 0; i < monedas.size(); i++){ 
      out.write("\n");
      out.write("\t\t\t\"<option value=\\\"");
      out.print(monedas.get(i).getCodigo());
      out.write('\\');
      out.write('"');
      out.write('>');
      out.print(monedas.get(i).getNombre());
      out.write("\"\n");
      out.write("\t\t\t\t+ \"</option>\" +\n");
      out.write("\t");
}
      out.write("\n");
      out.write("\t\t\"</select>\"\n");
      out.write("\t\t\t\t+ \"<div id=\\\"div_nueva_moneda_numContenido\\\" style=\\\"visibility: hidden; display: none; width: 0px; height: 0px;\\\">\"\n");
      out.write("\t\t\t\t+ \"<div class=\\\"tipo_titulo\\\">");
      out.print(traductor.traducir("codigo_moneda"));
      out.write(": <input type=\\\"text\\\" name=\\\"");
      out.print(Util.convertirANombreCampo(traductor.traducir("codigo_nueva_moneda")) );
      out.write("_numContenido\\\" size=\\\"6\\\" maxlength=\\\"10\\\"></div>\"\n");
      out.write("\t\t\t\t+ \"<div class=\\\"tipo_titulo\\\">");
      out.print(traductor.traducir("nombre_moneda"));
      out.write(": <input type=\\\"text\\\" name=\\\"");
      out.print(Util.convertirANombreCampo(traductor.traducir("nombre_nueva_moneda")) );
      out.write("_numContenido\\\"></div>\"\n");
      out.write("\t\t\t\t+ \"<div class=\\\"tipo_titulo\\\">");
      out.print(traductor.traducir("simbolo_moneda"));
      out.write(": <input type=\\\"text\\\" name=\\\"");
      out.print(Util.convertirANombreCampo(traductor.traducir("simbolo_nueva_moneda")) );
      out.write("_numContenido\\\" size=\\\"6\\\" maxlength=\\\"10\\\"></div>\"\n");
      out.write("\t\t\t\t+ \"<div class=\\\"tipo_titulo\\\">");
      out.print(traductor.traducir("valor_moneda"));
      out.write(": <input type=\\\"number\\\" name=\\\"");
      out.print(Util.convertirANombreCampo(traductor.traducir("valor_nueva_moneda")) );
      out.write("_numContenido\\\" step=\\\"any\\\" onkeypress=\\\"return soloNumerosConDecimales(event);\\\"></div></div>\"\n");
      out.write("\n");
      out.write("\t\t\t\t+ \"<input type=\\\"checkbox\\\" name=\\\"");
      out.print(Util.convertirANombreCampo(traductor.traducir("es_nueva_moneda")) );
      out.write("_numContenido\\\" value=\\\"true\\\" onchange=\\\"ocultarMostrar(this, Array('moneda_numContenido'), Array('div_nueva_moneda_numContenido'));\\\"> ");
      out.print(traductor.traducir("nueva_preguntando"));
      out.write("\"\n");
      out.write("\t\t\t\t+ \"</div>\" + \"</div>\";\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t");
if (request.getParameter("error") != null) {
      out.write("\n");
      out.write("\t\t\t\tmostrarMensaje(\"");
      out.print(traductor.traducir(request.getParameter("error")));
      out.write("\", true);\n");
      out.write("\t\t");
} else if (request.getParameter("mensaje_error") != null) {
      out.write("\n");
      out.write("\t\t\t\tmostrarMensaje(\"");
      out.print(request.getParameter("mensaje_error"));
      out.write("\", true);\n");
      out.write("\t\t");
} else if (request.getParameter("exito") != null) {
      out.write("\n");
      out.write("\t\t\t\tmostrarMensaje(\"");
      out.print(traductor.traducir(request.getParameter("exito")));
      out.write("\", false);\n");
      out.write("\t\t");
} else if (request.getParameter("mensaje_exito") != null) {
      out.write("\n");
      out.write("\t\t\t\tmostrarMensaje(\"");
      out.print(request.getParameter("mensaje_exito"));
      out.write("\", false);\n");
      out.write("\t\t");
}
      out.write("\n");
      out.write("\t</script>\n");
      out.write("\t");

		} catch (Exception e) {
			e.printStackTrace();
	
      out.write("\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\tmostrarMensaje(\"");
      out.print(e.getMessage());
      out.write("\n");
      out.write("\t\t\", true);\n");
      out.write("\t</script>\n");
      out.write("\t");

		}
	
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
