/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2014-07-26 19:24:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import modelo.utils.Util;
import modelo.utils.Traductor;
import modelo.utils.Traductor;
import modelo.utils.Traductor;
import modelo.utils.Traductor;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/jsp/plantillas/encabezado.jsp", Long.valueOf(1397991058000L));
    _jspx_dependants.put("/jsp/scripts/utils/validaciones.jsp", Long.valueOf(1398973020000L));
    _jspx_dependants.put("/jsp/plantillas/obj_idioma.jsp", Long.valueOf(1397991058000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('\n');
      out.write('	');
      out.write('\n');

	Traductor traductor = (Traductor) session.getAttribute("traductor");
	String[] idioma_pais = new String[2];
	String strIdiomaPais = "";
	if(traductor == null){
		String cookieName = "cookie_idioma_pais";
		Cookie cookies[] = request.getCookies();
		Cookie myCookie = null;
		if (cookies != null) {
			for (int i = 0; i < cookies.length; i++) {
				if (cookies[i].getName().equals(cookieName)) {
					myCookie = cookies[i];
					break;
				}
			}
		}
	
	
		if (myCookie == null) {
			traductor = new Traductor();
			idioma_pais[0] = traductor.getIdioma();
			idioma_pais[1] = traductor.getPais();
			myCookie = new Cookie(cookieName, idioma_pais[0] + "_"
					+ idioma_pais[1]);
			myCookie.setMaxAge(Integer.MAX_VALUE);
			response.addCookie(myCookie);
		} else {
			idioma_pais = myCookie.getValue().split("_");
			traductor = new Traductor(idioma_pais[0], idioma_pais[1]);
		}
		
		
		
	}else{
		idioma_pais[0] = traductor.getIdioma();
		idioma_pais[1] = traductor.getPais();
	}
	
		strIdiomaPais = idioma_pais[0] + "_" + idioma_pais[1];


	String[] idiomasDisponibles = traductor
			.getIdiomasPaisesDisponibles();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>");
      out.print(traductor.traducir("title_index"));
      out.write("</title>\n");
      out.write("<link type=\"text/css\" rel=\"StyleSheet\"\n");
      out.write("\thref=\"../css/plantillas/encabezado.css\">\n");
      out.write("<link type=\"text/css\" rel=\"StyleSheet\" href=\"../css/utils/errores.css\">\n");
      out.write("<link type=\"text/css\" rel=\"StyleSheet\" href=\"../css/index.css\">\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"../js/utils/utils.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"../js/utils/validaciones.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"../js/utils/cookies.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"../js/plantillas/idioma_pais.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"../js/index.js\"></script>\n");
      out.write("<script type=\"text/javascript\"\n");
      out.write("\tsrc=\"../js/ajax/llenar_cmb_grupo_equipos_ajax.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tvar cargando = \"");
      out.print(traductor.traducir("cargando"));
      out.write("\";\n");
      out.write("\tvar el_campo = \"");
      out.print(traductor.traducir("el_campo"));
      out.write("\";\n");
      out.write("\tvar es_requerido = \"");
      out.print(traductor.traducir("es_requerido"));
      out.write("\";\n");
      out.write("\tvar mensaje_email_invalido = \"");
      out.print(traductor.traducir("mensaje_email_invalido"));
      out.write("\";\n");
      out.write("\tvar titulo_errores_formulario = \"");
      out.print(traductor.traducir("titulo_errores_formulario"));
      out.write("\";\n");
      out.write("\tvar error_validar_imagen_parte1 = \"");
      out.print(traductor.traducir("error_validar_imagen_parte1"));
      out.write("\";\n");
      out.write("\tvar error_validar_video_parte1 = \"");
      out.print(traductor.traducir("error_validar_video_parte1"));
      out.write("\";\n");
      out.write("\tvar error_validar_archivo_parte1 = \"");
      out.print(traductor.traducir("error_validar_archivo_parte1"));
      out.write("\";\n");
      out.write("\tvar error_validar_archivo_parte2 = \"");
      out.print(traductor.traducir("error_validar_archivo_parte2"));
      out.write("\";\n");
      out.write("</script>");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t");

		try {
	
      out.write('\n');
      out.write('	');
      out.write("\n");
      out.write("\t\n");
      out.write("<div class=\"encabezado\">\n");
      out.write("\t<div class=\"texto_encabezado\">\n");
      out.write("\t\t<div class=\"titulo_encabezado\">");
      out.print(traductor.traducir("nombre_sistema") );
      out.write("</div>\n");
      out.write("\t\t<div class=\"subtitulo_encabezado\">");
      out.print(traductor.traducir("consola_administrativa") );
      out.write("</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"select_idiomas\">\n");
      out.write("\t\t<select id=\"select_idioma\" onchange=\"setIdiomaPais(this);\">\n");
      out.write("\t\t\t");

				for (int i = 0; i < idiomasDisponibles.length; i++) {
			
      out.write("\n");
      out.write("\t\t\t<option value=\"");
      out.print(idiomasDisponibles[i]);
      out.write("\"\n");
      out.write("\t\t\t\t");
if (idiomasDisponibles[i].equals(strIdiomaPais)) {
      out.write("\n");
      out.write("\t\t\t\tselected=\"selected\" ");
}
      out.write(">\n");
      out.write("\t\t\t\t");

					if (idiomasDisponibles[i].trim().length() > 0) {
							String idioma_pais2[] = idiomasDisponibles[i].split("_");
							Traductor t = new Traductor(idioma_pais2[0], idioma_pais2[1]);
							out.print(t.traducir(idioma_pais2[0]) + ", "
									+ t.traducir(idioma_pais2[1]));
						} else {
							out.print(traductor.traducir("default"));
						}
				
      out.write("\n");
      out.write("\t\t\t</option>\n");
      out.write("\t\t\t");

				}
			
      out.write("\n");
      out.write("\n");
      out.write("\t\t</select>\n");
      out.write("\t</div>\n");
      out.write("</div>");
      out.write("\n");
      out.write("\t<div id=\"cuerpo\">\n");
      out.write("\t\t<div id=\"error\" class=\"error\"></div>\n");
      out.write("\t\t<h2 class=\"titulo\">");
      out.print(traductor.traducir("titulo_index"));
      out.write("</h2>\n");
      out.write("\t\t<form method=\"post\"\n");
      out.write("\t\t\taction=\"");
      out.print(request.getContextPath() );
      out.write("/AutenticarUsuarioServlet\"\n");
      out.write("\t\t\tclass=\"form_autenticacion\" onsubmit=\"return validarFormulario(this);\">\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<span class=\"lbl_usuario\">");
      out.print(traductor.traducir("usuario"));
      out.write(":</span>\n");
      out.write("\t\t\t\t<input id=\"txtUsuario\" type=\"text\" maxlength=\"100\"\n");
      out.write("\t\t\t\t\tname=\"");
      out.print(Util.convertirANombreCampo(traductor
						.traducir("usuario")));
      out.write("\"\n");
      out.write("\t\t\t\t\trequired=\"required\" onchange=\"llenarGrupoEquipos();\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<span class=\"lbl_usuario\">");
      out.print(traductor.traducir("clave"));
      out.write(":</span> <input\n");
      out.write("\t\t\t\t\tid=\"pwdClave\" type=\"password\" maxlength=\"100\"\n");
      out.write("\t\t\t\t\tname=\"");
      out.print(Util.convertirANombreCampo(traductor
						.traducir("clave")));
      out.write("\"\n");
      out.write("\t\t\t\t\trequired=\"required\" onchange=\"llenarGrupoEquipos();\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<span class=\"lbl_usuario\">");
      out.print(traductor.traducir("grupo_de_equipos"));
      out.write(":</span>\n");
      out.write("\t\t\t\t<select id=\"cmbGrupoEquipos\"\n");
      out.write("\t\t\t\t\tname=\"");
      out.print(Util.convertirANombreCampo(traductor
						.traducir("grupo_de_equipos")));
      out.write("\"\n");
      out.write("\t\t\t\t\tdisabled=\"disabled\" required=\"required\">\n");
      out.write("\t\t\t\t\t<option value=\"\">");
      out.print(traductor.traducir("seleccione_un_grupo_de_equipos"));
      out.write("</option>\n");
      out.write("\t\t\t\t</select>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<br> <input type=\"hidden\" name=\"idioma_pais\"\n");
      out.write("\t\t\t\tvalue=\"");
      out.print(strIdiomaPais);
      out.write("\">\n");
      out.write("\t\t\t<div class=\"botones\">\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"");
      out.print(traductor.traducir("entrar"));
      out.write("\">\n");
      out.write("\t\t\t\t<input type=\"reset\" value=\"");
      out.print(traductor.traducir("reset"));
      out.write("\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</form>\n");
      out.write("\t\t<br>\n");
      out.write("\t\t<div class=\"recuperar_clave\">\n");
      out.write("\t\t\t<a\n");
      out.write("\t\t\t\tonclick=\"window.open('recuperar_clave.jsp', '");
      out.print(traductor.traducir("recuperar_clave").replaceAll(" ",
						"_"));
      out.write("', 'resizable=0,width=350,height=250,scrollbars=0,toolbar=0,status=0, position=absolute, top=50%, left=50%');\"\n");
      out.write("\t\t\t\thref=\"?\">");
      out.print(traductor.traducir("olvide_mi_clave"));
      out.write("</a>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t");
if (request.getParameter("error") != null) {
      out.write("\n");
      out.write("\t\t\tmostrarMensaje(\"");
      out.print(traductor.traducir(request.getParameter("error")));
      out.write("\", true);\n");
      out.write("\t");
} else if (request.getParameter("mensaje_error") != null) {
      out.write("\n");
      out.write("\t\t\tmostrarMensaje(\"");
      out.print(request.getParameter("mensaje_error"));
      out.write("\", true);\n");
      out.write("\t");
} else if (request.getParameter("exito") != null) {
      out.write("\n");
      out.write("\t\t\tmostrarMensaje(\"");
      out.print(traductor.traducir(request.getParameter("exito")));
      out.write("\", false);\n");
      out.write("\t");
} else if (request.getParameter("mensaje_exito") != null) {
      out.write("\n");
      out.write("\t\t\tmostrarMensaje(\"");
      out.print(request.getParameter("mensaje_exito"));
      out.write("\", false);\n");
      out.write("\t");
}
      out.write("\n");
      out.write("\t</script>\n");
      out.write("\t");

		} catch (Exception e) {
			e.printStackTrace();
	
      out.write("\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\tmostrarMensaje(\"");
      out.print(e.getMessage());
      out.write("\", true);\n");
      out.write("\t</script>\n");
      out.write("\t");

		}
	
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
